name: Domain Expiration Check
on:
  schedule:
    - cron: '0 */48 * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with: { python-version: '3.10' }
      - run: pip install requests
      - run: python domain_checker.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_IDS: ${{ secrets.CHAT_IDS }}
